<a href="https://colab.research.google.com/github/20193253/pdm10/blob/main/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [25]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [26]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# data.shape # Error!
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):
	print(data[row])

[1 2 3]
[4 5 6]


In [27]:
data.shape, data.shape[0], data.shape[1]

((2, 3), 2, 3)

## Print columns

In [28]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col])

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


---

## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [29]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [30]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [31]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


---

## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [DIY: 도전하기]

- 3차원 배열을 리스트로부터 만드시오.
- [참고: numpy_sum_axis](http://taewan.kim/post/numpy_sum_axis/)

In [ ]:
# Make 3d-array in numpy

from numpy import asarray
"""
data = [[1,2,3], [4,5,6]]
"""

In [47]:
data = [[[ 0,  1,  2,  3], [ 4,  5,  6,  7]], [[ 8,  9, 10, 11], [12, 13, 14, 15]], [[16, 17, 18, 19], [20, 21, 22, 23]], [[24, 25, 26, 27], [28, 29, 30, 31]]]
type(data)

list

In [48]:
data = asarray(data)
print(data)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]


In [49]:
print(data.ndim)

3


In [50]:
result = data.sum(axis=None)
print(result)

496


In [51]:
result = data.sum(axis=0)
print(result)

[[48 52 56 60]
 [64 68 72 76]]


In [52]:
result = data.sum(axis=1)
print(result)

[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]
