<a href="https://colab.research.google.com/github/20193253/pdm10/blob/main/numpy/numpy_3_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## random 서브모듈
> [데이터싸이언스 스쿨:난수발생](https://datascienceschool.net/01%20python/03.05%20%EB%82%9C%EC%88%98%20%EB%B0%9C%EC%83%9D%EA%B3%BC%20%EC%B9%B4%EC%9A%B4%ED%8C%85.html)

In [1]:
import numpy as np

## 난수 생성
> NumPy의 random 서브모듈은 난수를 생성하는 다양한 명령을 제공.

- rand: 0부터 1사이의 균일 분포 (uniform distribution)
- randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)
- randint: 균일 분포의 정수 난수 (uniform int)

> randn()은 평균 0, 표준편차 1 인 가우시안 정규분포를 생성.

### rand: 0부터 1사이의 균일 분포 (uniform distribution)

In [2]:
np.random.rand(5)

array([0.65559771, 0.13221024, 0.64591597, 0.32785895, 0.50299139])

In [3]:
np.random.rand(5)

array([0.57203546, 0.77050774, 0.99282971, 0.52667168, 0.69134203])

### randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)

In [4]:
np.random.randn(5)

array([-0.03144132, -0.83758343,  1.86822987, -0.64010934,  0.07350288])

In [5]:
np.random.randn(5)

array([ 1.38058878,  0.99296422, -0.2604355 , -0.16568779, -1.21213097])

### randint: 균일 분포의 정수 난수 (uniform int)
- numpy.random.randint(low, high=None, size=None, dtype='l')

In [8]:
np.random.randint(5)

2

In [10]:
# dice number
np.random.randint(1, 7)

6

In [11]:
np.random.randint(5,9) 

6

In [12]:
np.random.randint(0,10,5)

array([5, 0, 9, 1, 2])

In [13]:
np.random.randint(0,10,5)

array([5, 4, 6, 9, 1])

---

## 난수 생성 seed 설정
- numpy.random.seed(seed=None)
- np.random.seed(number)

In [14]:
np.random.seed()

In [15]:
np.random.rand(5)

array([0.92250818, 0.96890907, 0.3257906 , 0.61361431, 0.32650293])

In [16]:
np.random.rand(5)

array([0.72916681, 0.4699267 , 0.53090962, 0.64453259, 0.41331841])

### 동일한 무작위수 생성
- seed를 고정하고 무작위수 생성

In [17]:
np.random.seed(1234)

In [18]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [19]:
np.random.rand(5)

array([0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [20]:
np.random.seed(1234)

In [21]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

### seed 고정 후에 randint(5)

In [22]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [23]:
np.random.randint(1,10,5)

array([6, 3, 7, 4, 1])

In [24]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [25]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [26]:
# seed 변경
np.random.seed(0)
np.random.randint(1,10,5)

array([6, 1, 4, 4, 8])

---
---

## DIY: 도전 코딩 - numpy 정리 과제
- 생성된 마구잡이수를 조사하고 사용하기 
- 9월19일 자정 마감.

### [도전 1.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수의 빈도를 구하시오. 

In [29]:
# n1000=
n1000 = np.random.randint(0,10,1000)
n1000

array([8, 1, 0, 9, 5, 9, 2, 1, 3, 0, 6, 0, 7, 9, 3, 8, 4, 4, 5, 1, 6, 8,
       6, 1, 4, 4, 9, 8, 6, 2, 3, 8, 0, 5, 8, 7, 5, 6, 5, 7, 4, 2, 6, 6,
       8, 1, 0, 5, 0, 1, 4, 1, 9, 0, 3, 9, 3, 0, 8, 2, 5, 4, 2, 4, 2, 0,
       1, 5, 5, 8, 0, 0, 5, 7, 3, 6, 0, 2, 0, 5, 1, 7, 3, 2, 3, 2, 3, 7,
       7, 1, 4, 6, 7, 0, 0, 6, 4, 4, 5, 1, 2, 6, 8, 2, 9, 9, 5, 5, 8, 5,
       9, 1, 9, 4, 6, 9, 8, 0, 5, 6, 0, 6, 0, 6, 7, 1, 1, 5, 0, 6, 4, 4,
       4, 7, 2, 1, 4, 9, 8, 4, 4, 7, 0, 7, 8, 9, 9, 5, 2, 6, 9, 5, 6, 5,
       3, 3, 0, 3, 4, 1, 0, 9, 9, 3, 9, 3, 4, 6, 5, 7, 1, 5, 7, 6, 6, 6,
       1, 8, 4, 2, 0, 2, 8, 3, 7, 2, 1, 4, 4, 4, 2, 4, 8, 7, 9, 8, 9, 5,
       9, 1, 8, 8, 6, 0, 0, 2, 3, 2, 1, 9, 5, 6, 1, 8, 7, 7, 3, 4, 9, 6,
       9, 6, 4, 1, 2, 0, 0, 7, 6, 2, 9, 8, 8, 2, 1, 2, 7, 6, 6, 2, 1, 5,
       6, 9, 9, 3, 9, 4, 2, 1, 6, 0, 2, 6, 3, 7, 5, 2, 6, 6, 1, 9, 0, 1,
       3, 3, 1, 3, 4, 3, 9, 9, 5, 6, 8, 9, 5, 5, 8, 4, 5, 0, 3, 1, 6, 8,
       6, 3, 4, 5, 8, 2, 9, 3, 2, 9, 1, 1, 8, 6, 3,

In [31]:
# np.unique(n1000)

In [ ]:
# 각 수의 빈도

### [도전 2.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수가 처음 출현하는 인덱스를 구하시오.
> 0이 처음 나타날 때의 인덱스, 1이 처음 나타날 때의 인덱스, ... 

In [32]:
n1000[0], n1000[800]

(8, 8)

In [ ]:
# 각 수가 처음 출현하는 인덱스


In [ ]:
# n1000[index]

### [도전 3.] seed를 1234로 고정하고, 위의 도전1,2를 다시 해보시오. 

### [도전 4.] 0부터 999까지의 마구잡이 정수로 구성되는 28X28 이차원배열을 만드시오.
- 시드를 고정 : np.random.seed(1234)
1. 각 행의 최대값, 최소갑을 구하시오.
2. 배열 전체의 최대값, 최소값을 구하시오.
3. 배열전체의 최대값, 최소값의 index를 각각 찾으시오.

---
---

## python graphics
- matplotlib
> import matplotlib.pyplot as plt

### 무작위수 분포 그려보기

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(n1000,label=range(0,10), color='red')
# plt.show()

### [도전] 균일분포와 정규분포를 비교하는 그림을 그리시오.

In [ ]:
plt.hist(np.random.rand(1000))

In [ ]:
plt.hist(np.random.randn(1000))

## 보충 코드

In [36]:
n1000 = np.max(np.random.randint(0, 10, 1000))
n1000

9

In [37]:
value, count= np.unique(n1000, return_counts=True)

In [38]:
value, count

(array([9]), array([1]))